#!/usr/bin/env bash
# Display DNS information for a given domain and its subdomains

domain=$1
subdomain=$2

get_dns_info() {
    # List of all available subdomains
    subdomains=("www" "lb-01" "web-01" "web-02")
    # Extract the subdomain from the list if provided
    if [ "$subdomain" ]; then
        subdomains=("$subdomain")
    fi
    # Generate the dns audit info
    for sub in "${subdomains[@]}"; do
        dig +noall +answer "$sub.$domain" |
        awk -v _sub="$sub" '{print "The subdomain " _sub " is a " $4 " record and points to " $5}'
    done
}

get_dns_info "$domain" "$subdomain"
