#!/usr/bin/env bash
# Display DNS information for a given domain and its subdomains

# List of all available subdomains
subdomains=("www" "lb-01" "web-01" "web-02")

get_dns_info() {
    subdomain="$2"
    result=$(dig +noall +answer "$subdomain.$1")
    record=$(echo "$result" | awk '{print $4}')
    ip=$(echo "$result" | awk '{print $5}')
    echo "The subdomain $subdomain is a $record record and points to $ip"
}

if [ $# -eq 2 ]; then
    get_dns_info "$1" "$2"
    elif  [ $# -eq 1 ]; then
    for sub in "${subdomains[@]}"; do
        get_dns_info "$1" "$sub"
    done
fi
