#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server
# Accepts 4 parameters:
    # The path to the file to be transferred
    # The IP of the server we want to transfer the file to
    # The username scp connects with
    # The path to the SSH private key that scp uses

if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assigning parameters to variables
file_path="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

# Transfer file using scp
scp -o StrictHostKeyChecking=no "$file_path" "$ssh_key" "$username@$server_ip:~/" 
