#!/usr/bin/env bash
# Install nginx
sudo apt-get update -y
sudo apt-get install nginx -y
# Create a temporary HTML file with Hello World!
echo "Hello World!" > /var/www/html/index.nginx-debian.html
# Start nginx without systemctl
sudo service nginx start
