#!/usr/bin/env bash
# Install nginx
sudo apt-get -y update
sudo apt-get -y install nginx
# Nginx listens on port 80 by default
# Create a temporary HTML file with Hello World!
echo "Hello World!" | sudo /var/www/html/index.nginx.html
# Start nginx without systemctl
sudo service nginx start
