#!/usr/bin/env bash
# Script that configures nginx server

sudo apt-get update -y
sudo apt-get install nginx -y
# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
# Create index page
echo "<!DOCTYPE html><html><head><title>My Web Server</title></head><body style='font-family: Open Sans;'><h1 style='text-align: center; margin: 0; font-size: 5rem;'>Hello World!</h1></body></html>" > /var/www/html/index.nginx-debian.html
# Setting /redirect_me page to redirect to a youtube video
sudo sed -i '/listen [::]:80 default_server;/a rewrite ^/redirect_me https://www.github.com/AhmadYousif89 permanent;' /etc/nginx/sites-available/default
# Restarting nginx
sudo service nginx restart
