#!/usr/bin/env bash
# Script that configures nginx server

sudo apt-get update
sudo apt-get install nginx -y
# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
sudo ufw allow 'Nginx HTTP'
# Create index page
echo "Hello World!" > /var/www/html/index.nginx-debian.html
# Setting /redirect_me page to redirect to a youtube video
sudo sed -i '/^server {/a    \\trewrite ^/redirect_me https://www.github.com/AhmadYousif89 permanent;' /etc/nginx/sites-available/default
# Restarting nginx
sudo service nginx restart
