#!/usr/bin/env bash
# Script that configures nginx server

if ! command -v nginx &> /dev/null; then
    sudo apt-get update
    sudo apt-get -y install nginx
fi
# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www
sudo chmod -R 755 /var/www
# Create index page
echo "Hello World!" > /var/www/html/index.html
# Setting /redirect_me page to redirect to a youtube video
sudo sed -i '/^server {/a    \\trewrite ^/redirect_me https://www.github.com/AhmadYousif89 permanent;' /etc/nginx/sites-enabled/default
# Setting custom not-found page /404
echo "Page Not Found!" > /var/www/html/error_404.html
sudo sed -i '46i	\\terror_page 404 /error_404.html;' /etc/nginx/sites-enabled/default
# Restarting nginx
sudo service nginx restart
