#!/usr/bin/env bash
# script that installs and configure a Ngnix web server and adds a custom header.

sudo apt-get update
sudo apt-get install nginx -y
# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
echo "<!DOCTYPE html><html><head><title>My Web Server</title></head><body style='font-family: Open Sans;'><h1 style='text-align: center; margin: 0; font-size: 5rem;'>Hello World!</h1></body></html>" > /var/www/html/index.nginx-debian.html
# Configure Nginx to add custom header
sudo sed -i '/^http {/a \\tadd_header X-Served-By "'"$HOSTNAME"'";' /etc/nginx/nginx.conf
sudo service nginx restart
