#!/usr/bin/env bash
# script that installs and configure a HAproxy on a Load-Balancer server.

PORT=80
web_01_name="530995-web-01"
web_01_ip="34.224.62.175"
web_02_name="530995-web-02"
web_02_ip="54.84.8.54"

# Install required packages
sudo apt update
sudo apt-get install haproxy -y
# Backup HAProxy configuration file
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
# Append server configuration to HAProxy configuration file
sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null <<EOF

frontend jo-tech-http
    bind *:$PORT
    mode http
    default_backend jo-tech-backend

backend jo-tech-backend
    balance roundrobin
    server  $web_01_name    $web_01_ip:$PORT    check
    server  $web_02_name    $web_02_ip:$PORT    check

EOF
# Restart the HAproxy service
sudo service haproxy restart
