#!/usr/bin/env bash
# script that installs and configure a HAproxy on a Load-Balancer server.

# shellcheck source=SERVER_COFIG_FILE
SERVER_COFIG_FILE="/home/ubuntu/servers.conf"
source $SERVER_COFIG_FILE
PORT=80
# Ensure script exits if any command fails
set -e
# Install required packages
sudo apt-get install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.8 -y
sudo apt-get install haproxy=2.8.\* -y
# Backup HAProxy configuration file
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
# Append server configuration to HAProxy configuration file
sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null <<EOF

frontend haproxy_lb
    bind *:$PORT
    mode http
    default_backend web_servers

backend web_servers
    balance roundrobin
    server  $web_01_name    $web_01_ip:$PORT    check
    server  $web_02_name    $web_02_ip:$PORT    check

EOF
# Restart the HAproxy service
sudo systemctl restart haproxy
