#!/usr/bin/env bash
# backup and compress my databases
# Usage: ./backup.sh <password>

DUMP_FILENAME="backup.sql"
# Compressed archive filename format: day-month-year.tar.gz
ARCHIVE_FILENAME="$(date +'%d-%m-%Y').tar.gz"
# Dump all databases and compress it
mysqldump -u root -p"$1" --all-databases > "$DUMP_FILENAME"
tar -czf "$ARCHIVE_FILENAME" "$DUMP_FILENAME"
