#!/usr/bin/env bash
# Script that configures a server with Nginx web server

# Install Nginx if not already installed
if ! command -v nginx &> /dev/null; then
    sudo apt update
    sudo apt install -y nginx
fi

sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default 

# Start Nginx if not running
if ! sudo service nginx status &> /dev/null; then
    sudo service nginx restart
fi
