#!/usr/bin/env bash
# Script that configures a server with Nginx web server

# Install Nginx if not already installed
if ! command -v nginx &> /dev/null; then
    sudo apt update
    sudo apt install -y nginx
fi

cd /etc/nginx/sites-enabled/ && rm default;
ln -s /etc/nginx/sites-available/default default;   

sudo service nginx restart
