#!/usr/bin/env bash
# Script that writes its process ID to a file, handles termination signals,
#+ and runs an infinite loop echoing a message, demonstrating signal trapping.
#+ SIGTERM and SIGINT display messages, and SIGQUIT triggers a cleanup function
#+ that removes the process ID file.

filename="/var/run/myscript.pid"

terminator() {
  rm $filename
  exit
}

echo "$$" > $filename

trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "I hate the kill command" && terminator' SIGTERM
trap 'terminator' SIGQUIT 

while true; do
  echo "To infinity and beyond"
  sleep 2
done
