#!/usr/bin/env bash
# Script that that manages the (manage_my_process) script.
#+ When passing the argument start:
	# Starts manage_my_process
	# Creates a file containing its PID in /var/run/my_process.pid
	# Displays manage_my_process started
#+ When passing the argument stop:
	# Stops manage_my_process
	# Deletes the file /var/run/my_process.pid
	# Displays manage_my_process stopped
#+ When passing the argument restart
	# Stops manage_my_process
	# Deletes the file /var/run/my_process.pid
	# Starts manage_my_process
	# Creates a file containing its PID in /var/run/my_process.pid
	# Displays manage_my_process restarted
#+ Displays Usage: manage_my_process {start|stop|restart} if any other argument or no argument is passed

process_name="manage_my_process"
pid_file="/var/run/my_process.pid"

if [ "${1}" == "start" ]; then
	./manage_my_process &
    echo $! > $pid_file
    echo "$process_name started"
elif [ "${1}" == "stop" ]; then
	kill "$(cat $pid_file)"
	rm $pid_file
	echo "$process_name stopped"
elif [ "${1}" == "restart" ]; then
	kill "$(cat $pid_file)"
	rm $pid_file
	echo "$process_name stopped"
	./manage_my_process &
    echo $! > $pid_file 
    echo "$process_name started"
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
