#!/usr/bin/env bash
# Script that displays information about the file /etc/passwd:
#+	Format: The user USERNAME is part of the GROUP_ID gang, lives in HOME_DIRECTORY and rides COMMAND/SHELL. USER ID's place is protected by the passcode PASSWORD, more info about the user here: USER ID INFO

while IFS=":" read -r username x uid gid info home shell; do
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $x, more info about the user here: $info"
done < "/etc/passwd"
