#!/usr/bin/env bash
# Script that displays the visitor IP along with the HTTP status code from the Apache log file using the AWK command.
#+ while counting the number of occurances for each IP.

awk '{print $1, $9}' apache-access.log | sort | uniq -c | sort -nr | awk '{print $1, $2, $3}'
