#!/usr/bin/env bash
# Script that loops 10 times using a While loop and: 
#+ prints "bad luck" for the 4th loop iteration.
#+ prints "good luck" for the 8th loop iteration.
#+ prints "Best School" for the other iterations.

i=1

while [ $i -le 10 ]; do
	if [ $i -eq 4 ]; then
		echo "bad luck"
	elif [ $i -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	i=$((i+1))
done
