#!/usr/bin/env bash
# Script that prints numbers and loops 20 times using match casing in a While loop and: 
#+ prints '4' and then "bad luck from China" for the 4th loop iteration.
#+ prints '9' and then "bad luck from Japan" for the 9th loop iteration.
#+ prints '17' and then "bad luck from Italy" for the 17th loop iteration.

i=1
string="bad luck from"

while [ $i -le 20 ]; do
	case  $i in
		4)
		echo "4" && echo "$string China"
		;;
		9)
		echo "9" && echo "$string Japan"
		;;
		17)
		echo "17" && echo "$string Italy"
		;;
		*)
		echo "$i"
		;;
	esac
	i=$((i+1))
done
