#!/usr/bin/env bash
#  Script that displays:
#+ The content of the current directory in a list format
#+ where only the part of the name after the first dash is displayed

for file in *; do
    # Check if the file is not hidden and is a regular file
    if [[ ! $file == .* && -f $file ]]; then
        name_after_dash=$(echo "$file" | cut -d '-' -f2)
        echo "$name_after_dash"
    fi
done