#!/usr/bin/env bash
#  Script that displays information about the (school) file:

filename="school"
# check if exist
if [ -a "$filename" ]; then
	echo "$filename file exists"
	# check if empty
	if [ -s "$filename" ]; then
		echo "$filename file is not empty"
	else
		echo "$filename file is empty"
	fi
	# check if is regular file
	if [ -f "$filename" ]; then
		echo "$filename is a regular file"
	fi
else
	echo "$filename file does not exist"
fi
