#!/usr/bin/bash

# Configure ufw so that it blocks all incoming traffic, except the following TCP ports: 
# 22 (SSH), 443 (HTTPS SSL), 80 (HTTP)

if ! command -v ufw &> /dev/null; then
    sudo apt update
    sudo apt install ufw -y
fi

sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
echo "y" | sudo ufw enable
sudo ufw status verbose
