#!/usr/bin/bash

# Configure ufw so that it blocks all incoming traffic, except the following TCP ports: 
# 22 (SSH), 443 (HTTPS SSL), 80 (HTTP)

if ! command -v ufw &> /dev/null; then
    sudo apt update
    sudo apt install ufw -y
fi

sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
echo "y" | sudo ufw enable
sudo ufw status verbose

# A rule to allow any incoming connections from the replica server (web-02) IP address to 
# the primary server (web-01) to its MySQL’s default port number 3306:
# sudo ufw delete allow from 'web-02_ip_address' to any port 3306
