#!/usr/bin/env bash
# Script that configures an Ubuntu server with the below requirements:
#+ localhost resolves to 127.0.0.2
#+ facebook.com resolves to 8.8.8.8.

cp /etc/hosts ~/hosts.new
sed -i -e '/localhost$/s/127.0.0.1/127.0.0.2/' -e '/localhost$/a\8.8.8.8\t\tfacebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
